force-app/main/default/objects/Service_Setting__mdt/Service_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object is used to manage all Services(APIs) used in the system.</description>
    <label>Service Setting</label>
    <pluralLabel>Service Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Setting__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Contains the API method name</description>
    <inlineHelpText>Contains the API method name</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Setting__mdt/fields/Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Named_Credential__c</fullName>
    <description>Contains the Named Credential API name</description>
    <inlineHelpText>Named Credential API name</inlineHelpText>
    <label>Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Setting__mdt/fields/Request_Header_Values__c.field-meta.xml
<CustomField>
    <fullName>Request_Header_Values__c</fullName>
    <description>Used to store Request Header Values</description>
    <inlineHelpText>API Request Header Values, names should be comma separated.</inlineHelpText>
    <label>Request Header Values</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Setting__mdt/fields/RequestHeaderKeys__c.field-meta.xml
<CustomField>
    <fullName>RequestHeaderKeys__c</fullName>
    <description>Used to store API header keys</description>
    <inlineHelpText>API header keys, and names should be comma separated.</inlineHelpText>
    <label>Request Header Keys</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Service_Setting__mdt/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <description>contains API endpoint path</description>
    <inlineHelpText>API endpoint Path</inlineHelpText>
    <label>Resource</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Setting__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <description>The default timeout is 10 seconds. A custom timeout can be defined for each callout. The minimum is 1 millisecond and the maximum is 120,000 milliseconds.</description>
    <inlineHelpText>The minimum is 1 millisecond and the maximum is 120,000 milliseconds.</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceAPI.cls
/**
* Utilities class for API calls.
*Common class handling HTTP calls.
* @date    12/08/2022
* @author  Sudhakar Y
*/

public with Sharing class ServiceAPI {  
    
    
    /**
* @description : This method is used to invoke the HTTP Requests
* @param serviceName : Contains the Service Settings name
* @param body : Contains API Request Body data
* @param extraParams : Contains all the extra params required for this service call
* @return HttpResponse
*/
    public static HttpResponse callService(String serviceName, String body,  Map<string, Object> extraParams) {
        try {
            
            Service_Setting__mdt service = Service_Setting__mdt.getInstance(serviceName);
            if(service==NULL){
                throw new CustomException('Service Not Found');
            }
            
            String endPoint = 'callout:' + service.Named_Credential__c;
            endPoint += service.Resource__c;          
            
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endPoint);
            request.setMethod(service.Method__c);
            
            if(service.Timeout__c!=null){
                request.setTimeout((Integer) service.Timeout__c);  
            } 
            
            if(body!=null){
                request.setBody(body);  
            }
            
            // set headers in request and exception            
            List<String> headers = service.RequestHeaderKeys__c.split(',');
            List<String> headerValues = service.Request_Header_Values__c.split(',');
            Integer i = 0;
            for(String s: headers){
                request.setHeader(s, headerValues[i]);
                i++;
            }
            
            System.debug('request ++'+request.getBody());
            HttpResponse response = http.send(request);
            System.debug('response ++'+response.getBody()); 
            // if((response.getStatusCode() == 200) || (response.getStatusCode() == 201)) {                
            return response;
            // }            
            
        } catch(Exception e){
            system.debug('Line '+e.getLineNumber());
            customException.LogException(e);
            //log error
            return null;
            
        }
    }
    
}