force-app/main/default/objects/System_Log__c/System_Log__c.object-meta.xml
<CustomObject>
    <description>Logging object to store exception messages generated by Apex or Integrations.</description>
    <label>System Log</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <description>Source Apex class</description>
    <inlineHelpText>Source Apex class</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Source Apex method</description>
    <inlineHelpText>Source Apex method</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <description>Error identifier</description>
    <inlineHelpText>Error identifier</inlineHelpText>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Related_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_Record_Id__c</fullName>
    <description>Id of record related to message</description>
    <inlineHelpText>Id of record related to message</inlineHelpText>
    <label>Related Record Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <description>HTTP Call Response Status Code</description>
    <inlineHelpText>HTTP Call Response Status Code</inlineHelpText>
    <label>Response Code</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <description>HTTP API Service call name</description>
    <inlineHelpText>HTTP API Service call name</inlineHelpText>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Apex stack trace</description>
    <inlineHelpText>Apex stack trace</inlineHelpText>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomException.cls
@SuppressWarnings('PMD.ApexCRUDViolation')
/**
* @Name CustomException
* @description  Custom exception class to log the all exceptions in system log object.
* @date    13/08/2022
* @author  Sudhakar Y
*/

public with Sharing class CustomException extends Exception{
    /**
* @description : This method is used to log exception record in system log object
* @param Exception : Contains the Service Settings name
* @return void
*/   
    public static void logException(Exception e)
    {
        LogException(e,'');
    }
    
    /**
* @description : This method is used to log exception record in system log object
* @param Exception : Contains the Service Settings name
* @param relatedToId : Contains API Request Body data
* @return void
*/
    
    public static void logException(Exception e,string relatedToId)
    {
        try
        {
            String stackTrace = e.getStackTraceString().substringBefore('\n');
            String className = stackTrace.substringAfter('.').substringBefore('.');	
            String methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');          
            
            
            //Log information in System_Log object
            System_Log__c exc = new System_Log__c();
            exc.Related_Record_Id__c=relatedToId;
            exc.Stack_Trace__c = e.getMessage();
            exc.Reference__c = e.getTypeName();
            exc.Response_Code__c = e.getLineNumber();
            exc.Service_Name__c = e.getStackTraceString();
            exc.Method__c=methodName;
            exc.Class__c=className;
            database.insert(exc); 
            // Loop save result and handle the error records if any.
        }catch(Exception ex){
            system.debug(''+ex.getCause()); 
        }
                  
    } 
}