force-app/main/default/objects/SMS_History__c/SMS_History__c.object-meta.xml
<CustomObject>
    <description>This Object stores information about Outgoing SMS.</description>
    <label>SMS History</label>
    <nameField>
        <displayFormat>SMS-{0000000}</displayFormat>
        <label>SMS History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the ID of the related Account.</description>
    <inlineHelpText>This field contains the ID of the related Account.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SMS History</relationshipLabel>
    <relationshipName>SMS_History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Account_Sid__c.field-meta.xml
<CustomField>
    <fullName>Account_Sid__c</fullName>
    <description>Account SID</description>
    <inlineHelpText>Account SID</inlineHelpText>
    <label>Account Sid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/body__c.field-meta.xml
<CustomField>
    <fullName>body__c</fullName>
    <description>It store the SMS body</description>
    <inlineHelpText>It store the SMS body</inlineHelpText>
    <label>Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <description>This field contains the SMS Created On date.</description>
    <inlineHelpText>This field contains the SMS Created On date.</inlineHelpText>
    <label>Date Created</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Date_Sent__c.field-meta.xml
<CustomField>
    <fullName>Date_Sent__c</fullName>
    <description>This field contains the SMS Sent On date.</description>
    <inlineHelpText>This field contains the SMS Sent On date.</inlineHelpText>
    <label>Date Sent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Date_Updated__c.field-meta.xml
<CustomField>
    <fullName>Date_Updated__c</fullName>
    <description>This field contains the latest SMS Status Updated On date.</description>
    <inlineHelpText>This field contains the latest SMS Status Updated On date.</inlineHelpText>
    <label>Date Updated</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>This field contains the ERROR Code, if status is UNDELIVERED</description>
    <label>Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This field contains the error messsage</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/from__c.field-meta.xml
<CustomField>
    <fullName>from__c</fullName>
    <description>This field contains the Sender&apos;s phone number.</description>
    <inlineHelpText>This field contains the Sender&apos;s phone number.</inlineHelpText>
    <label>From</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/SID__c.field-meta.xml
<CustomField>
    <fullName>SID__c</fullName>
    <description>It contains the SMS Record SID</description>
    <inlineHelpText>It contains the SMS Record SID</inlineHelpText>
    <label>SID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <description>This field contains the status of the message. The status can be Sent, Submitted, Queued, etc.</description>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>This field contains the mobile number of the recipient.</description>
    <label>To</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SMS_History__c/fields/URI__c.field-meta.xml
<CustomField>
    <fullName>URI__c</fullName>
    <description>A URI aims to identify a resource and differentiate it from other resources</description>
    <inlineHelpText>A URI aims to identify a resource and differentiate it from other resources</inlineHelpText>
    <label>URI</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Twilio_SMS_Settings__mdt/Twilio_SMS_Settings__mdt.object-meta.xml
<CustomObject>
    <description>Twilio SMS Settings used to map Sender and Recipient(CEO) phone number mapping</description>
    <label>Twilio SMS Settings</label>
    <pluralLabel>Twilio SMS Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Twilio_SMS_Settings__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to deactivate the SMS functionality</description>
    <inlineHelpText>Used to deactivate the SMS functionality</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Twilio_SMS_Settings__mdt/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <description>sender Phone number, copied from Twilio console app settings</description>
    <inlineHelpText>sender Phone number, copied from Twilio console app settings</inlineHelpText>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Twilio_SMS_Settings__mdt/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <description>Used to store CEO Phone Number</description>
    <inlineHelpText>Used to store CEO Phone Number</inlineHelpText>
    <label>To</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMS_Utils.cls
@SuppressWarnings('PMD.AvoidGlobalModifier,PMD.ExcessiveParameterList,PMD.CyclomaticComplexity,PMD.ApexCRUDViolation')
/**
* @Name SMS_Utils
* @description Twilio SMS  Utilities class.
* @date    12/08/2022
* @author  Sudhakar Y
*/
global with Sharing class SMS_Utils {  
    
    /**
* @description : This is InvocableMethod method used in Flows to invoke APex action to send SMS
* @param List<smsRequest> : its custom wrapper class Contains (smsSettingsName, smsBody and recordID) variables
* @return List<smsResponse> : its custom wrapper class Contains
*/  
    @InvocableMethod(label='Send SMS' description='Send SMS to customer mobile number')
    global  static List<SMSResponse> getSMSRequests(List<smsRequest> smsRequestList) {        
        List<SMSResponse> smsResponseList = new List<SMSResponse>();
        List<TwilioSMSJSONRESPONSE> smsWrapperList = new List<TwilioSMSJSONRESPONSE>();
        for(smsRequest sms : smsRequestList)
        {
            system.debug('HI ++++'+sms);
            Twilio_SMS_Settings__mdt twilioSMSSetting = Twilio_SMS_Settings__mdt.getInstance(sms.smsSettingsName);
            if(string.isNotBlank(sms.smsSettingsName) && twilioSMSSetting!=NULL
               && twilioSMSSetting.Active__c){
                   
                   TwilioSMSJSONRESPONSE response= SendSMS(twilioSMSSetting.From__c,twilioSMSSetting.To__c, sms.smsBody.replaceAll('<[/a-zAZ0-9]*>',''));
                   
                   SMSResponse res= new SMSResponse();
                   res.Id=SMS.RecordId;  
                   
                   if(response!=NULL){
                       response.SobjectId =SMS.RecordId;
                       response.from_number =twilioSMSSetting.From__c;
                       smsWrapperList.add(response);
                       res.goldNotificationSend=true;                            
                   }
                   else{
                       res.goldNotificationSend=false;  
                   }
                   
                   smsResponseList.add(res);
               }
        }
        
        insertSMSlogs(smsWrapperList);       
        return smsResponseList;       
    }
    
    
    /**
* @description : This method is used to Send SMS
* @param Phone_From : Contains the sender phone number
* @param Phone_To : Contains recipient phone number
* @param Body : Contains SMS Body string
* @return TwilioSMSJSONRESPONSE
*/  
    public  static TwilioSMSJSONRESPONSE sendSMS(String phoneFrom, String phoneTo,  String body){
        try{
            String smsReqBody= 'Body=' + EncodingUtil.urlEncode(body, 'UTF-8')
                + '&From=' + EncodingUtil.urlEncode(phoneFrom, 'UTF-8')
                + '&To=' + EncodingUtil.urlEncode(phoneTo, 'UTF-8');
            
            Map<String, object> extraParams = new Map<String, object>{'RecordId' =>''};
                
                HttpResponse response=ServiceAPI.callService('twilio_SMS',smsReqBody,NULL);
            
            // if((response.getStatusCode() == 200) || (response.getStatusCode() == 201)){  
            return  (TwilioSMSJSONRESPONSE)System.JSON.deserialize(response.getBody(), TwilioSMSJSONRESPONSE.class);           
            
            // }
            // return NULL;
        }
        catch(Exception ex){
            customException.logException(ex);
            return NULL;
        }
        
    }
    
    /**
* @description : This method is used to Insert SMS logs into SMS History object 
* @param smsWrapperList : Contains List of ALL SMS response logs
* @return void
*/ 
    public  static void insertSMSlogs(List<TwilioSMSJSONRESPONSE> smsWrapperList){
        try{
            List<SMS_History__c> smsHistoryList = new List<SMS_History__c>();
            for(TwilioSMSJSONRESPONSE smsRec:smsWrapperList){
                SMS_History__c smsEntry= New SMS_History__c();
                if(smsRec.SobjectId.startsWith('001')){
                    smsEntry.Account__c=smsRec.SobjectId;   
                }/*else if(smsRec.SobjectId.startsWith('003')){
                    smsEntry.Contact__c=smsRec.SobjectId;   // To enable SMS History tracking for contact
                } */          
                smsEntry.Account_Sid__c=smsRec.account_sid;
                smsEntry.body__c=smsRec.body;
                smsEntry.Date_Created__c=smsRec.date_created;
                smsEntry.Date_Sent__c=smsRec.date_sent;
                smsEntry.Error_Code__c=smsRec.error_code;
                smsEntry.Error_Message__c=smsRec.error_message;
                smsEntry.from__c=smsRec.from_number;
                smsEntry.status__c=smsRec.status;
                smsEntry.To__c=smsRec.to;
                smsEntry.Date_Updated__c=smsRec.date_updated;
                smsEntry.SID__c=smsRec.sid;
                smsEntry.URI__c=smsRec.uri;
                smsHistoryList.add(smsEntry);
            }
            database.insert(smsHistoryList,false); // The partial insert is supported.
            // Loop save result and handle the error records if any.           
        }
        catch(Exception ex){
            customException.logException(ex);
        }
    }    
    
    /**
* @description : This is Wrapper class used in Flow to include all required params in input request
*/ 
    global  class SMSRequest {
        @InvocableVariable(Required=true)
        global  String smsSettingsName; // Custom metadata record name
        
        @InvocableVariable(Required=true)
        global  String recordId;  // sobject record Id     
        
        @InvocableVariable(required=true)
        global  String smsBody; //SMS Body
    }
    
    /**
* @description : This is Wrapper class used in Flow to send response
*/ 
    global  class SMSResponse {
        @InvocableVariable(Required=true)
        global  String id; // sobject record Id
        
        @InvocableVariable(Required=true)
        global  boolean goldNotificationSend; // Flag to identify the SMS status     
        
    }    
}